name: siru_thozhilagam
description: A voice-based job finder app for blue-collar workers.
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  speech_to_text: ^5.8.0
  google_fonts: ^4.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/